/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  m.ambros
 * Created: 5. 6. 2020
 */
INSERT INTO co.t_cocktails_x_ingredients VALUES (189, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (189, 38);
INSERT INTO co.t_cocktails_x_ingredients VALUES (189, 39);
INSERT INTO co.t_cocktails_x_ingredients VALUES (190, 40);
INSERT INTO co.t_cocktails_x_ingredients VALUES (190, 41);
INSERT INTO co.t_cocktails_x_ingredients VALUES (190, 42);
INSERT INTO co.t_cocktails_x_ingredients VALUES (191, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (191, 44);
INSERT INTO co.t_cocktails_x_ingredients VALUES (191, 45);
INSERT INTO co.t_cocktails_x_ingredients VALUES (192, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (192, 46);
INSERT INTO co.t_cocktails_x_ingredients VALUES (193, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (193, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (193, 48);
INSERT INTO co.t_cocktails_x_ingredients VALUES (193, 49);
INSERT INTO co.t_cocktails_x_ingredients VALUES (193, 50);
INSERT INTO co.t_cocktails_x_ingredients VALUES (194, 51);
INSERT INTO co.t_cocktails_x_ingredients VALUES (194, 40);
INSERT INTO co.t_cocktails_x_ingredients VALUES (194, 41);
INSERT INTO co.t_cocktails_x_ingredients VALUES (194, 52);
INSERT INTO co.t_cocktails_x_ingredients VALUES (195, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (195, 46);
INSERT INTO co.t_cocktails_x_ingredients VALUES (195, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (196, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (196, 40);
INSERT INTO co.t_cocktails_x_ingredients VALUES (197, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (197, 54);
INSERT INTO co.t_cocktails_x_ingredients VALUES (197, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (198, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (198, 50);
INSERT INTO co.t_cocktails_x_ingredients VALUES (198, 55);
INSERT INTO co.t_cocktails_x_ingredients VALUES (198, 56);
INSERT INTO co.t_cocktails_x_ingredients VALUES (199, 57);
INSERT INTO co.t_cocktails_x_ingredients VALUES (199, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (199, 58);
INSERT INTO co.t_cocktails_x_ingredients VALUES (199, 59);
INSERT INTO co.t_cocktails_x_ingredients VALUES (199, 60);
INSERT INTO co.t_cocktails_x_ingredients VALUES (200, 54);
INSERT INTO co.t_cocktails_x_ingredients VALUES (200, 61);
INSERT INTO co.t_cocktails_x_ingredients VALUES (200, 40);
INSERT INTO co.t_cocktails_x_ingredients VALUES (200, 62);
INSERT INTO co.t_cocktails_x_ingredients VALUES (201, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (201, 63);
INSERT INTO co.t_cocktails_x_ingredients VALUES (201, 46);
INSERT INTO co.t_cocktails_x_ingredients VALUES (202, 54);
INSERT INTO co.t_cocktails_x_ingredients VALUES (202, 52);
INSERT INTO co.t_cocktails_x_ingredients VALUES (202, 64);
INSERT INTO co.t_cocktails_x_ingredients VALUES (202, 65);
INSERT INTO co.t_cocktails_x_ingredients VALUES (202, 66);
INSERT INTO co.t_cocktails_x_ingredients VALUES (203, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (203, 67);
INSERT INTO co.t_cocktails_x_ingredients VALUES (203, 68);
INSERT INTO co.t_cocktails_x_ingredients VALUES (204, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (204, 54);
INSERT INTO co.t_cocktails_x_ingredients VALUES (204, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (205, 69);
INSERT INTO co.t_cocktails_x_ingredients VALUES (205, 70);
INSERT INTO co.t_cocktails_x_ingredients VALUES (206, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (206, 48);
INSERT INTO co.t_cocktails_x_ingredients VALUES (206, 50);
INSERT INTO co.t_cocktails_x_ingredients VALUES (207, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (207, 71);
INSERT INTO co.t_cocktails_x_ingredients VALUES (208, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (208, 40);
INSERT INTO co.t_cocktails_x_ingredients VALUES (208, 46);
INSERT INTO co.t_cocktails_x_ingredients VALUES (208, 72);
INSERT INTO co.t_cocktails_x_ingredients VALUES (208, 53);
INSERT INTO co.t_cocktails_x_ingredients VALUES (209, 73);
INSERT INTO co.t_cocktails_x_ingredients VALUES (209, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (209, 40);
INSERT INTO co.t_cocktails_x_ingredients VALUES (209, 74);
INSERT INTO co.t_cocktails_x_ingredients VALUES (209, 75);
INSERT INTO co.t_cocktails_x_ingredients VALUES (210, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (210, 51);
INSERT INTO co.t_cocktails_x_ingredients VALUES (210, 67);
INSERT INTO co.t_cocktails_x_ingredients VALUES (210, 76);
INSERT INTO co.t_cocktails_x_ingredients VALUES (210, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (210, 77);
INSERT INTO co.t_cocktails_x_ingredients VALUES (211, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (211, 79);
INSERT INTO co.t_cocktails_x_ingredients VALUES (212, 80);
INSERT INTO co.t_cocktails_x_ingredients VALUES (212, 81);
INSERT INTO co.t_cocktails_x_ingredients VALUES (212, 50);
INSERT INTO co.t_cocktails_x_ingredients VALUES (212, 82);
INSERT INTO co.t_cocktails_x_ingredients VALUES (212, 83);
INSERT INTO co.t_cocktails_x_ingredients VALUES (212, 84);
INSERT INTO co.t_cocktails_x_ingredients VALUES (212, 85);
INSERT INTO co.t_cocktails_x_ingredients VALUES (214, 80);
INSERT INTO co.t_cocktails_x_ingredients VALUES (214, 86);
INSERT INTO co.t_cocktails_x_ingredients VALUES (214, 87);
INSERT INTO co.t_cocktails_x_ingredients VALUES (214, 88);
INSERT INTO co.t_cocktails_x_ingredients VALUES (215, 89);
INSERT INTO co.t_cocktails_x_ingredients VALUES (215, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (215, 90);
INSERT INTO co.t_cocktails_x_ingredients VALUES (215, 50);
INSERT INTO co.t_cocktails_x_ingredients VALUES (216, 37);
INSERT INTO co.t_cocktails_x_ingredients VALUES (216, 77);
INSERT INTO co.t_cocktails_x_ingredients VALUES (217, 91);
INSERT INTO co.t_cocktails_x_ingredients VALUES (217, 92);
INSERT INTO co.t_cocktails_x_ingredients VALUES (217, 48);
INSERT INTO co.t_cocktails_x_ingredients VALUES (217, 68);
INSERT INTO co.t_cocktails_x_ingredients VALUES (217, 39);
INSERT INTO co.t_cocktails_x_ingredients VALUES (218, 38);
INSERT INTO co.t_cocktails_x_ingredients VALUES (218, 71);
INSERT INTO co.t_cocktails_x_ingredients VALUES (218, 39);
INSERT INTO co.t_cocktails_x_ingredients VALUES (219, 93);
INSERT INTO co.t_cocktails_x_ingredients VALUES (219, 94);
INSERT INTO co.t_cocktails_x_ingredients VALUES (219, 95);
INSERT INTO co.t_cocktails_x_ingredients VALUES (220, 89);
INSERT INTO co.t_cocktails_x_ingredients VALUES (220, 68);
INSERT INTO co.t_cocktails_x_ingredients VALUES (221, 80);
INSERT INTO co.t_cocktails_x_ingredients VALUES (221, 88);
INSERT INTO co.t_cocktails_x_ingredients VALUES (221, 96);
INSERT INTO co.t_cocktails_x_ingredients VALUES (222, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (222, 68);
INSERT INTO co.t_cocktails_x_ingredients VALUES (222, 98);
INSERT INTO co.t_cocktails_x_ingredients VALUES (223, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (223, 80);
INSERT INTO co.t_cocktails_x_ingredients VALUES (223, 99);
INSERT INTO co.t_cocktails_x_ingredients VALUES (224, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (224, 100);
INSERT INTO co.t_cocktails_x_ingredients VALUES (224, 101);
INSERT INTO co.t_cocktails_x_ingredients VALUES (224, 58);
INSERT INTO co.t_cocktails_x_ingredients VALUES (225, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (225, 92);
INSERT INTO co.t_cocktails_x_ingredients VALUES (225, 102);
INSERT INTO co.t_cocktails_x_ingredients VALUES (225, 87);
INSERT INTO co.t_cocktails_x_ingredients VALUES (225, 78);
INSERT INTO co.t_cocktails_x_ingredients VALUES (226, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (227, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (227, 50);
INSERT INTO co.t_cocktails_x_ingredients VALUES (227, 90);
INSERT INTO co.t_cocktails_x_ingredients VALUES (228, 103);
INSERT INTO co.t_cocktails_x_ingredients VALUES (228, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (228, 101);
INSERT INTO co.t_cocktails_x_ingredients VALUES (228, 46);
INSERT INTO co.t_cocktails_x_ingredients VALUES (228, 58);
INSERT INTO co.t_cocktails_x_ingredients VALUES (228, 90);
INSERT INTO co.t_cocktails_x_ingredients VALUES (229, 103);
INSERT INTO co.t_cocktails_x_ingredients VALUES (229, 104);
INSERT INTO co.t_cocktails_x_ingredients VALUES (229, 105);
INSERT INTO co.t_cocktails_x_ingredients VALUES (229, 58);
INSERT INTO co.t_cocktails_x_ingredients VALUES (230, 97);
INSERT INTO co.t_cocktails_x_ingredients VALUES (231, 51);
INSERT INTO co.t_cocktails_x_ingredients VALUES (231, 106);
INSERT INTO co.t_cocktails_x_ingredients VALUES (231, 105);
INSERT INTO co.t_cocktails_x_ingredients VALUES (232, 54);
INSERT INTO co.t_cocktails_x_ingredients VALUES (232, 107);
INSERT INTO co.t_cocktails_x_ingredients VALUES (232, 108);
INSERT INTO co.t_cocktails_x_ingredients VALUES (233, 43);
INSERT INTO co.t_cocktails_x_ingredients VALUES (233, 109);
INSERT INTO co.t_cocktails_x_ingredients VALUES (234, 110);
INSERT INTO co.t_cocktails_x_ingredients VALUES (234, 40);
INSERT INTO co.t_cocktails_x_ingredients VALUES (234, 59);
INSERT INTO co.t_cocktails_x_ingredients VALUES (234, 62);
INSERT INTO co.t_cocktails_x_ingredients VALUES (235, 47);
INSERT INTO co.t_cocktails_x_ingredients VALUES (235, 49);
INSERT INTO co.t_cocktails_x_ingredients VALUES (235, 92);
INSERT INTO co.t_cocktails_x_ingredients VALUES (235, 48);
INSERT INTO co.t_cocktails_x_ingredients VALUES (235, 87);

SELECT pg_catalog.setval('co.t_cocktails_x_ingredients_cocktail_id_seq', 1, false);
SELECT pg_catalog.setval('co.t_cocktails_x_ingredients_ingredients_id_seq', 1, false);

INSERT INTO co.t_cocktails VALUES (189, 'Alexander', 'https://en.wikipedia.org//wiki/Alexander_(cocktail)');
INSERT INTO co.t_cocktails VALUES (190, 'Americano', 'https://en.wikipedia.org//wiki/Americano_(cocktail)');
INSERT INTO co.t_cocktails VALUES (191, 'Angel Face', 'https://en.wikipedia.org//wiki/Angel_Face_(cocktail)');
INSERT INTO co.t_cocktails VALUES (192, 'Aviation', 'https://en.wikipedia.org//wiki/Aviation_(cocktail)');
INSERT INTO co.t_cocktails VALUES (193, 'Between the Sheets', 'https://en.wikipedia.org//wiki/Between_the_Sheets_(cocktail)');
INSERT INTO co.t_cocktails VALUES (194, 'Boulevardier', 'https://en.wikipedia.org//wiki/Boulevardier_(cocktail)');
INSERT INTO co.t_cocktails VALUES (195, 'Casino', 'https://en.wikipedia.org//wiki/Casino_(cocktail)');
INSERT INTO co.t_cocktails VALUES (196, 'Dry Martini', 'https://en.wikipedia.org//wiki/Martini_(cocktail)');
INSERT INTO co.t_cocktails VALUES (197, 'Fizz', 'https://en.wikipedia.org//wiki/Fizz_(cocktail)#Gin_fizz');
INSERT INTO co.t_cocktails VALUES (198, 'John Collins', 'https://en.wikipedia.org//wiki/John_Collins_(cocktail)');
INSERT INTO co.t_cocktails VALUES (199, 'The Last Word', 'https://en.wikipedia.org//wiki/Last_Word_(cocktail)');
INSERT INTO co.t_cocktails VALUES (200, 'Manhattan', 'https://en.wikipedia.org//wiki/Manhattan_(cocktail)');
INSERT INTO co.t_cocktails VALUES (201, 'Mary Pickford', 'https://en.wikipedia.org//wiki/Mary_Pickford_(cocktail)');
INSERT INTO co.t_cocktails VALUES (202, 'Old Fashioned', 'https://en.wikipedia.org//wiki/Old_fashioned_(cocktail)');
INSERT INTO co.t_cocktails VALUES (203, 'Paradise', 'https://en.wikipedia.org//wiki/Paradise_(cocktail)');
INSERT INTO co.t_cocktails VALUES (204, 'Fizz', 'https://en.wikipedia.org//wiki/Fizz_(cocktail)#Ramos_gin_fizz');
INSERT INTO co.t_cocktails VALUES (205, 'Rusty Nail', 'https://en.wikipedia.org//wiki/Rusty_Nail_(cocktail)');
INSERT INTO co.t_cocktails VALUES (206, 'Sidecar', 'https://en.wikipedia.org//wiki/Sidecar_(cocktail)');
INSERT INTO co.t_cocktails VALUES (207, 'Stinger', 'https://en.wikipedia.org//wiki/Stinger_(cocktail)');
INSERT INTO co.t_cocktails VALUES (208, 'Tuxedo', 'https://en.wikipedia.org//wiki/Tuxedo_(cocktail)');
INSERT INTO co.t_cocktails VALUES (209, 'Vieux Carré', 'https://en.wikipedia.org//wiki/Vieux_Carr%C3%A9_(cocktail)');
INSERT INTO co.t_cocktails VALUES (210, 'Sours', 'https://en.wikipedia.org//wiki/Sour_(cocktail)#White_Lady');
INSERT INTO co.t_cocktails VALUES (211, 'Bellini', 'https://en.wikipedia.org//wiki/Bellini_(cocktail)');
INSERT INTO co.t_cocktails VALUES (212, 'Bloody Mary', 'https://en.wikipedia.org//wiki/Bloody_Mary_(cocktail)');
INSERT INTO co.t_cocktails VALUES (213, 'Corpse Reviver №1', 'https://en.wikipedia.org//wiki/Corpse_Reviver_(cocktail)');
INSERT INTO co.t_cocktails VALUES (214, 'Cosmopolitan', 'https://en.wikipedia.org//wiki/Cosmopolitan_(cocktail)');
INSERT INTO co.t_cocktails VALUES (215, 'French 75', 'https://en.wikipedia.org//wiki/French_75_(cocktail)');
INSERT INTO co.t_cocktails VALUES (216, 'French Connection', 'https://en.wikipedia.org//wiki/French_Connection_(cocktail)');
INSERT INTO co.t_cocktails VALUES (217, 'Golden Dream', 'https://en.wikipedia.org//wiki/Golden_dream_(cocktail)');
INSERT INTO co.t_cocktails VALUES (218, 'Grasshopper', 'https://en.wikipedia.org//wiki/Grasshopper_(cocktail)');
INSERT INTO co.t_cocktails VALUES (219, 'Kir', 'https://en.wikipedia.org//wiki/Kir_(cocktail)');
INSERT INTO co.t_cocktails VALUES (220, 'Mimosa', 'https://en.wikipedia.org//wiki/Mimosa_(cocktail)');
INSERT INTO co.t_cocktails VALUES (221, 'Sea Breeze', 'https://en.wikipedia.org//wiki/Sea_Breeze_(cocktail)');
INSERT INTO co.t_cocktails VALUES (222, 'Tequila Sunrise', 'https://en.wikipedia.org//wiki/Tequila_Sunrise_(cocktail)');
INSERT INTO co.t_cocktails VALUES (223, 'Vesper', 'https://en.wikipedia.org//wiki/Vesper_(cocktail)');
INSERT INTO co.t_cocktails VALUES (224, 'Zombie', 'https://en.wikipedia.org//wiki/Zombie_(cocktail)');
INSERT INTO co.t_cocktails VALUES (225, 'Barracuda', 'https://en.wikipedia.org//wiki/Barracuda_(cocktail)');
INSERT INTO co.t_cocktails VALUES (226, 'Bee''s Knees', 'https://en.wikipedia.org//wiki/Bee%27s_Knees_(cocktail)');
INSERT INTO co.t_cocktails VALUES (227, 'Bramble', 'https://en.wikipedia.org//wiki/Bramble_(cocktail)');
INSERT INTO co.t_cocktails VALUES (228, 'Illegal', 'https://en.wikipedia.org//wiki/Illegal_(cocktail)');
INSERT INTO co.t_cocktails VALUES (229, 'Naked and Famous', 'https://en.wikipedia.org//wiki/Naked_and_Famous_(cocktail)');
INSERT INTO co.t_cocktails VALUES (230, 'Paloma', 'https://en.wikipedia.org//wiki/Paloma_(cocktail)');
INSERT INTO co.t_cocktails VALUES (231, 'Paper Plane', 'https://en.wikipedia.org//wiki/Paper_Plane_(cocktail)');
INSERT INTO co.t_cocktails VALUES (232, 'Penicillin', 'https://en.wikipedia.org//wiki/Penicillin_(cocktail)');
INSERT INTO co.t_cocktails VALUES (233, 'South Side or Southside', 'https://en.wikipedia.org//wiki/Southside_(cocktail)');
INSERT INTO co.t_cocktails VALUES (234, 'Tipperary', 'https://en.wikipedia.org//wiki/Tipperary_(cocktail)');
INSERT INTO co.t_cocktails VALUES (235, 'Yellow Bird', 'https://en.wikipedia.org//wiki/Yellow_Bird_(cocktail)');

SELECT pg_catalog.setval('co.t_cocktails_cocktail_id_seq', 235, true);

INSERT INTO co.t_ingredients VALUES (37, 'cognac');
INSERT INTO co.t_ingredients VALUES (38, 'crème de cacao');
INSERT INTO co.t_ingredients VALUES (39, 'cream');
INSERT INTO co.t_ingredients VALUES (40, 'vermouth');
INSERT INTO co.t_ingredients VALUES (41, 'campari');
INSERT INTO co.t_ingredients VALUES (42, 'soda water');
INSERT INTO co.t_ingredients VALUES (43, 'gin');
INSERT INTO co.t_ingredients VALUES (44, 'calvados');
INSERT INTO co.t_ingredients VALUES (45, 'apricot brandy');
INSERT INTO co.t_ingredients VALUES (46, 'maraschino');
INSERT INTO co.t_ingredients VALUES (47, 'rum');
INSERT INTO co.t_ingredients VALUES (48, 'triple sec');
INSERT INTO co.t_ingredients VALUES (49, 'white rum');
INSERT INTO co.t_ingredients VALUES (50, 'lemon juice');
INSERT INTO co.t_ingredients VALUES (51, 'bourbon whiskey');
INSERT INTO co.t_ingredients VALUES (52, 'bourbon');
INSERT INTO co.t_ingredients VALUES (53, 'orange bitters');
INSERT INTO co.t_ingredients VALUES (54, 'whiskey');
INSERT INTO co.t_ingredients VALUES (55, 'sugar syrup');
INSERT INTO co.t_ingredients VALUES (56, 'carbonated water');
INSERT INTO co.t_ingredients VALUES (57, 'green chartreuse');
INSERT INTO co.t_ingredients VALUES (58, 'lime');
INSERT INTO co.t_ingredients VALUES (59, 'chartreuse');
INSERT INTO co.t_ingredients VALUES (60, 'maraschino liqueur');
INSERT INTO co.t_ingredients VALUES (61, 'cl');
INSERT INTO co.t_ingredients VALUES (62, 'angostura bitters');
INSERT INTO co.t_ingredients VALUES (63, 'grenadine');
INSERT INTO co.t_ingredients VALUES (64, 'dashes');
INSERT INTO co.t_ingredients VALUES (65, 'sugar');
INSERT INTO co.t_ingredients VALUES (66, 'water');
INSERT INTO co.t_ingredients VALUES (67, 'brandy');
INSERT INTO co.t_ingredients VALUES (68, 'orange juice');
INSERT INTO co.t_ingredients VALUES (69, 'scotch whisky');
INSERT INTO co.t_ingredients VALUES (70, 'drambuie');
INSERT INTO co.t_ingredients VALUES (71, 'crème de menthe');
INSERT INTO co.t_ingredients VALUES (72, 'absinthe');
INSERT INTO co.t_ingredients VALUES (73, 'rye whiskey');
INSERT INTO co.t_ingredients VALUES (74, 'bénédictine');
INSERT INTO co.t_ingredients VALUES (75, 'peychaud''s bitters');
INSERT INTO co.t_ingredients VALUES (76, 'pisco');
INSERT INTO co.t_ingredients VALUES (77, 'amaretto');
INSERT INTO co.t_ingredients VALUES (78, 'prosecco');
INSERT INTO co.t_ingredients VALUES (79, 'peach');
INSERT INTO co.t_ingredients VALUES (80, 'vodka');
INSERT INTO co.t_ingredients VALUES (81, 'tomato juice');
INSERT INTO co.t_ingredients VALUES (82, 'worcestershire sauce');
INSERT INTO co.t_ingredients VALUES (83, 'tabasco sauce');
INSERT INTO co.t_ingredients VALUES (84, 'celery salt');
INSERT INTO co.t_ingredients VALUES (85, 'black pepper');
INSERT INTO co.t_ingredients VALUES (86, 'cointreau');
INSERT INTO co.t_ingredients VALUES (87, 'lime juice');
INSERT INTO co.t_ingredients VALUES (88, 'cranberry juice');
INSERT INTO co.t_ingredients VALUES (89, 'champagne');
INSERT INTO co.t_ingredients VALUES (90, 'simple syrup');
INSERT INTO co.t_ingredients VALUES (91, 'orange-flavored liqueur');
INSERT INTO co.t_ingredients VALUES (92, 'galliano');
INSERT INTO co.t_ingredients VALUES (93, 'wine');
INSERT INTO co.t_ingredients VALUES (94, 'white wine');
INSERT INTO co.t_ingredients VALUES (95, 'crème de cassis');
INSERT INTO co.t_ingredients VALUES (96, 'grapefruit juice');
INSERT INTO co.t_ingredients VALUES (97, 'tequila');
INSERT INTO co.t_ingredients VALUES (98, 'grenadine syrup');
INSERT INTO co.t_ingredients VALUES (99, 'lillet blanc');
INSERT INTO co.t_ingredients VALUES (100, 'golden rum');
INSERT INTO co.t_ingredients VALUES (101, 'falernum');
INSERT INTO co.t_ingredients VALUES (102, 'pineapple juice');
INSERT INTO co.t_ingredients VALUES (103, 'mezcal');
INSERT INTO co.t_ingredients VALUES (104, 'yellow chartreuse');
INSERT INTO co.t_ingredients VALUES (105, 'aperol');
INSERT INTO co.t_ingredients VALUES (106, 'amaro');
INSERT INTO co.t_ingredients VALUES (107, 'blended scotch whiskey');
INSERT INTO co.t_ingredients VALUES (108, 'lagavulin 16y whiskey');
INSERT INTO co.t_ingredients VALUES (109, '[1]');
INSERT INTO co.t_ingredients VALUES (110, 'irish whiskey');

SELECT pg_catalog.setval('co.t_ingredients_ingredient_id_seq', 110, true);
